Create-ledger test description 'test ledger' seed 'cambridge'
create-account mary
create-account bob
create-account bill
create-account susan
create-account jack
get-account-balance mary
process-transaction 1 amount 1000 fee 10 payload 'fund account' payer master receiver mary
process-transaction 2 amount 1000 fee 10 payload 'fund account' payer master receiver bob
process-transaction 3 amount 1000 fee 10 payload 'fund account' payer master receiver bill
process-transaction 4 amount 1000 fee 10 payload 'fund account' payer master receiver susan
process-transaction 5 amount 1000 fee 10 payload 'fund account' payer master receiver mary
get-account-balance mary
get-account-balances
process-transaction 6 amount 1000 fee 10 payload 'fund account' payer master receiver bob
process-transaction 7 amount 1000 fee 10 payload 'fund account' payer master receiver bill
process-transaction 8 amount 1000 fee 10 payload 'fund account' payer master receiver susan
process-transaction 9 amount 1000 fee 10 payload 'fund account' payer master receiver mary
process-transaction 10 amount 1000 fee 10 payload 'fund account' payer master receiver bob
get-account-balance mary
get-account-balance bob
get-account-balance bill
get-account-balance susan
get-account-balance jack
get-block 1
get-transaction 10
process-transaction 11 amount 200 fee 10 payload 'september rent' payer susan receiver jack
get-account-balance susan
get-account-balance jack
process-transaction 12 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 13 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 14 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 15 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 16 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 17 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 18 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 19 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
process-transaction 20 amount 20 fee 10 payload 'uber pay' payer bob receiver mary
get-account-balance jack
get-account-balance susan
get-account-balance mary
get-account-balance bob
get-account-balances
process-transaction 21 amount 5000 fee 10 payload 'food pay' payer bob receiver mary
process-transaction 22 amount 20 fee 5 payload 'food pay' payer bob receiver mary
Validate